server {
    listen 8080;
    server_name localhost;

    location / {
        root www;
        allowed_methods GET;
        autoindex on;
    }
}

server {
    listen 9000;
    server_name test_server;
}